# This file was generated by GoReleaser. DO NOT EDIT.
cask "pgwd" do
  version "0.9.0"

  on_macos do
    on_intel do
      sha256 "1646f759d530ffa853b011cc112f60e102af6a87fd1aeb218387f62d4762155e"
      url "https://github.com/hrodrig/pgwd/releases/download/v#{version}/pgwd_v#{version}_darwin_amd64.tar.gz",
        verified: "github.com/hrodrig/pgwd/"
    end
    on_arm do
      sha256 "45a01d0d1627e1f6918ff86b125820d1925544c3ed03cd99078f95e2852d5924"
      url "https://github.com/hrodrig/pgwd/releases/download/v#{version}/pgwd_v#{version}_darwin_arm64.tar.gz",
        verified: "github.com/hrodrig/pgwd/"
    end
  end

  on_linux do
    on_intel do
      sha256 "01614f98d1130e3845919a6da2d87126854fec9a495b162f182ff6e57a57432c"
      url "https://github.com/hrodrig/pgwd/releases/download/v#{version}/pgwd_v#{version}_linux_amd64.tar.gz",
        verified: "github.com/hrodrig/pgwd/"
    end
    on_arm do
      sha256 "555b6bfae66e6066e6cc646f49139ff3639d6a344bb634ee9256fd8736e91e2d"
      url "https://github.com/hrodrig/pgwd/releases/download/v#{version}/pgwd_v#{version}_linux_arm64.tar.gz",
        verified: "github.com/hrodrig/pgwd/"
    end
  end

  name "pgwd"
  desc "Postgres Watch Dog - monitor PostgreSQL connections and notify via Slack/Loki"
  homepage "https://github.com/hrodrig/pgwd"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pgwd"
  manpage "share/man/man1/pgwd.1"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/pgwd"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Sample configuration is not bundled with the Homebrew cask.
    Generate it with `pgwd --print-sample-config > /etc/pgwd/pgwd.conf`.
  EOS
end
