# This file was generated by GoReleaser. DO NOT EDIT.
cask "pgwd" do
  name "pgwd"
  desc "Postgres Watch Dog - monitor PostgreSQL connections and notify via Slack/Loki"
  homepage "https://github.com/hrodrig/pgwd"
  version "0.5.0"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pgwd"

  on_macos do
    on_intel do
      url "https://github.com/hrodrig/pgwd/releases/download/v#{version}/pgwd_v#{version}_darwin_amd64.tar.gz",
        verified: "github.com/hrodrig/pgwd/"
      sha256 "4672eb7bfdfa0f4f6c631f7975cc3ad5d784cf5a2b66dfee4962be22ec516db9"
    end
    on_arm do
      url "https://github.com/hrodrig/pgwd/releases/download/v#{version}/pgwd_v#{version}_darwin_arm64.tar.gz",
        verified: "github.com/hrodrig/pgwd/"
      sha256 "4230a1d4033c3f804989e6edb44a361eefe1622399586b6b1c2128aecd2ee455"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/hrodrig/pgwd/releases/download/v#{version}/pgwd_v#{version}_linux_amd64.tar.gz",
        verified: "github.com/hrodrig/pgwd/"
      sha256 "6e46ffecfb16852808af021002762bf780e32e2a2cce194a03e04e44b650f2a8"
    end
    on_arm do
      url "https://github.com/hrodrig/pgwd/releases/download/v#{version}/pgwd_v#{version}_linux_arm64.tar.gz",
        verified: "github.com/hrodrig/pgwd/"
      sha256 "8514943c0dda98ee1293410fd716c72165d1ae6bed78c906f9dfb5bef91243ec"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/pgwd"]
    end
  end

  # No zap stanza required
end
