# This file was generated by GoReleaser. DO NOT EDIT.
cask "pgwd" do
  version "0.7.0"

  on_macos do
    on_intel do
      sha256 "51f13fe380634e29d4ee66d1badc13618f68bc407d09b85f135bf20bb4d5f347"
      url "https://github.com/hrodrig/pgwd/releases/download/v#{version}/pgwd_v#{version}_darwin_amd64.tar.gz",
        verified: "github.com/hrodrig/pgwd/"
    end
    on_arm do
      sha256 "da04cbb9ede69a603c0d66f263317da743255bfeba1cbd932fb0bd814f844358"
      url "https://github.com/hrodrig/pgwd/releases/download/v#{version}/pgwd_v#{version}_darwin_arm64.tar.gz",
        verified: "github.com/hrodrig/pgwd/"
    end
  end

  on_linux do
    on_intel do
      sha256 "9295fc80e1d3c10bfdf6800825a8d7d5202f9860109dd066476729f896421c31"
      url "https://github.com/hrodrig/pgwd/releases/download/v#{version}/pgwd_v#{version}_linux_amd64.tar.gz",
        verified: "github.com/hrodrig/pgwd/"
    end
    on_arm do
      sha256 "568ec87e94413369a752977a92be205e7b049d5ae3582238d831eae45be4df07"
      url "https://github.com/hrodrig/pgwd/releases/download/v#{version}/pgwd_v#{version}_linux_arm64.tar.gz",
        verified: "github.com/hrodrig/pgwd/"
    end
  end

  name "pgwd"
  desc "Postgres Watch Dog - monitor PostgreSQL connections and notify via Slack/Loki"
  homepage "https://github.com/hrodrig/pgwd"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "pgwd"
  manpage "share/man/man1/pgwd.1"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/pgwd"]
    end
  end

  # No zap stanza required

  caveats <<~EOS
    Sample configuration is not bundled with the Homebrew cask.
    Generate it with `pgwd --print-sample-config > /etc/pgwd/pgwd.conf`.
  EOS
end
